class AppAssets {
  AppAssets._();

  static const splashBackground = 'lib/assets/images/splash_background.png';
  static const appFullLogo = 'lib/assets/svg/app_full_logo.svg';
  static const appWhiteLogo = 'lib/assets/svg/app_white_logo.svg';
  static const balanceIcon = 'lib/assets/svg/balance_icon.svg';
  static const cardIcon = 'lib/assets/svg/card_icon.svg';
  static const dashboardIcon = 'lib/assets/svg/dashboard_icon.svg';
  static const dateIcon = 'lib/assets/svg/date_icon.svg';
  static const detailsIcon = 'lib/assets/svg/details_icon.svg';
  static const editIcon = 'lib/assets/svg/edit_icon.svg';
  static const helpIcon = 'lib/assets/svg/help_icon.svg';
  static const linkIcon = 'lib/assets/svg/link_icon.svg';
  static const scanIcon = 'lib/assets/svg/scan_icon.svg';
  static const nextIcon = 'lib/assets/svg/next_icon.svg';
  static const notificationsIcon = 'lib/assets/svg/notifications_icon.svg';
  static const paymentIcon = 'lib/assets/svg/payment_icon.svg';
  static const staticQrIcon = 'lib/assets/svg/static_qr_icon.svg';
  static const supportIcon = 'lib/assets/svg/support_icon.svg';
  static const totalSalesIcon = 'lib/assets/svg/total_sales_icon.svg';
  static const walletIcon = 'lib/assets/svg/wallet_icon.svg';
  static const backIcon = 'lib/assets/svg/back_icon.svg';
  static const contactlessIcon = 'lib/assets/svg/contactless_icon.svg';
  static const keyBadIcon = 'lib/assets/svg/key_bad_icon.svg';
  static const expressLogo = 'lib/assets/images/express_logo.png';
  static const masterLogo = 'lib/assets/images/master_logo.png';
  static const omanNetLogo = 'lib/assets/images/oman_net_logo.png';
  static const visaLogo = 'lib/assets/images/visa_logo.png';
  static const qrScan = 'lib/assets/images/qr_scan.png';
  static const cvvIcon = 'lib/assets/svg/cvv_icon.svg';
  static const contactLessImageIcon = 'lib/assets/svg/contactless_image.svg';
  static const arrowUpIcon = 'lib/assets/svg/arrow_up_icon.svg';
  static const arrowDownIcon = 'lib/assets/svg/arrow_down_icon.svg';
  static const downArrowIcon = 'lib/assets/svg/down_arrow.svg';
  static const errorIcon = 'lib/assets/svg/error_icon.svg';
  static const successIcon = 'lib/assets/svg/successfully_icon.svg';
  static const successfullyIcon = 'lib/assets/svg/successfully_icon.svg';
  static const onBoardingIcon1 = 'lib/assets/images/fast_easy_image.png';
  static const onBoardingIcon2 = 'lib/assets/images/secure_image.png';
  static const onBoardingIcon3 = 'lib/assets/images/support_image.png';
  static const divCircleRight = 'lib/assets/images/div_circle_right.png';
  static const divCircleLeft = 'lib/assets/images/div_circle_left.png';
  static const flashIcon = 'lib/assets/svg/flash_icon.svg';
  static const logOutIcon = 'lib/assets/svg/logout_icon.svg';
  static const transactionIcon = 'lib/assets/svg/transaction_icon.svg';
}
